apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  selector:
    matchLabels:
      app: order
  replicas: 2 
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: rupahli/order-management:40
        ports:
        - containerPort: 8889