apiVersion: v1
kind: Service
metadata:
  name: order-deployment
  labels:
    apps: order-deployment
spec:
  type: LoadBalancer
  ports:
    - port: 8889
      targetPort: 80
      name: order-deployment
  selector:
    app: order-deployment