apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
spec:
  selector:
    matchLabels:
      app: inventory
  replicas: 2 
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory
        image: rupahli/inventory-management:1
        ports:
        - containerPort: 8888