spring:
  profiles:
    active: dev
rest:
  url: http://localhost:8085/invProducts
  token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDk5NzUyMTAsInVzZXJfbmFtZSI6ImthbmRhbiIsImF1dGhvcml0aWVzIjpbIlJPTEVfQURNSU4iXSwianRpIjoiYTc5YTZkOTctYjY2Ny00Njc4LTkzNWItYzlhYmM0ZjQyOWVhIiwiY2xpZW50X2lkIjoiY2xpZW50aWQiLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXX0.SG5KqQZOfJqGkxeips21WXDTFnQPzIsrXfqFFXMTuUTk-mCpaCb0GDIjdioic5agg_MQ6F61RrSfgnsYjDGUkPSr9nNOpm7-9HZJZcBzhiOfnRw9AvskDCYYI1T-FwyJe0o3wyjzTIL25Mh6_KW91chBZ5hrQT_3UEnLFJhmL_0JhSr1SYKkqKySv5fZjqp_shVCzBdjEdBjRsusOkv1AxsE11OPkxmeEZlzsjvL9sEUNu7xi5zqmxpMZTom_y2ztuL9hfZyrAye489vQVME2Q2HWvxL0HphNzmCq4S7SbN66NHdnyiF4FoTzKJJTUO9gekdVeTmXgh1E5xuNHqeOA

---
spring:
  profiles: dev
server:
  servlet:
    context-path: /dev
  port: 8888
rest:
  url: http://localhost:8888/dev/invProducts
  token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDk5NzUyMTAsInVzZXJfbmFtZSI6ImthbmRhbiIsImF1dGhvcml0aWVzIjpbIlJPTEVfQURNSU4iXSwianRpIjoiYTc5YTZkOTctYjY2Ny00Njc4LTkzNWItYzlhYmM0ZjQyOWVhIiwiY2xpZW50X2lkIjoiY2xpZW50aWQiLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXX0.SG5KqQZOfJqGkxeips21WXDTFnQPzIsrXfqFFXMTuUTk-mCpaCb0GDIjdioic5agg_MQ6F61RrSfgnsYjDGUkPSr9nNOpm7-9HZJZcBzhiOfnRw9AvskDCYYI1T-FwyJe0o3wyjzTIL25Mh6_KW91chBZ5hrQT_3UEnLFJhmL_0JhSr1SYKkqKySv5fZjqp_shVCzBdjEdBjRsusOkv1AxsE11OPkxmeEZlzsjvL9sEUNu7xi5zqmxpMZTom_y2ztuL9hfZyrAye489vQVME2Q2HWvxL0HphNzmCq4S7SbN66NHdnyiF4FoTzKJJTUO9gekdVeTmXgh1E5xuNHqeOA

---
spring:
  profiles: prod
server:
  servlet:
    context-path: /
  port: 9999
rest:
  url: http://localhost:8085/invProducts
  token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDk5NzUyMTAsInVzZXJfbmFtZSI6ImthbmRhbiIsImF1dGhvcml0aWVzIjpbIlJPTEVfQURNSU4iXSwianRpIjoiYTc5YTZkOTctYjY2Ny00Njc4LTkzNWItYzlhYmM0ZjQyOWVhIiwiY2xpZW50X2lkIjoiY2xpZW50aWQiLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXX0.SG5KqQZOfJqGkxeips21WXDTFnQPzIsrXfqFFXMTuUTk-mCpaCb0GDIjdioic5agg_MQ6F61RrSfgnsYjDGUkPSr9nNOpm7-9HZJZcBzhiOfnRw9AvskDCYYI1T-FwyJe0o3wyjzTIL25Mh6_KW91chBZ5hrQT_3UEnLFJhmL_0JhSr1SYKkqKySv5fZjqp_shVCzBdjEdBjRsusOkv1AxsE11OPkxmeEZlzsjvL9sEUNu7xi5zqmxpMZTom_y2ztuL9hfZyrAye489vQVME2Q2HWvxL0HphNzmCq4S7SbN66NHdnyiF4FoTzKJJTUO9gekdVeTmXgh1E5xuNHqeOA